// Generated by CoffeeScript 1.7.1
(function() {
  var canvas;

  window.Backgroud = (function() {
    function Backgroud() {}

    Backgroud.prototype.draw = function(context) {
      context.fillStyle = '#000';
      return context.fillRect(0, 0, game.width, game.height);
    };

    return Backgroud;

  })();

  window.Score = (function() {
    function Score(player, x, y) {
      this.player = player;
      this.x = x;
      this.y = y;
    }

    Score.prototype.draw = function(context) {
      context.fillStyle = '#fff';
      context.font = '40px monospace';
      return context.fillText(this.player.score, this.x, this.y);
    };

    return Score;

  })();

  canvas = ($('canvas'))[0];

  window.game = new Game(canvas);

  game.addEntity(new Backgroud());

  game.addEntity(new Ball(), 'ball');

  game.addEntity(new Player(), 'player');

  game.addEntity(new Bot(), 'bot');

  game.addEntity(new Score(game.player, game.width * 3 / 8, 50));

  game.addEntity(new Score(game.bot, game.width * 5 / 8, 50));

  game.start();

  canvas.focus();

}).call(this);
